javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls Card.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls Deck.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls HandPanel.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls Player.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls AbstractGameStage.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls GameStage1P.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls GameStage2P.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls GameStage3P.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls MainMenu.java
javac --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls Main.java
java --module-path d:\Codes\Java\javafx-sdk-11.0.2\lib --add-modules javafx.controls Main
